%YAML 1.2
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
replayer: # VideoStreamReplayer
  basename: "anonymization"
  frame_rate: 30 # as specified in timestamps
  repeat: true # default: false
  realtime: true # default: true
  count: 0 # default: 0 (no frame count restriction)
  directory: "orsi"

aja: # AJASourceOp
  width: 1920
  height: 1080
  rdma: true
  enable_overlay: false

out_of_body_format_converter:
  out_tensor_name: source_video
  out_dtype: "float32"
  src_roi_rect: [328, 36, 1264, 1008]
  output_img_size: [224, 224]

out_of_body_normalizer:
  in_tensor_name: source_video
  out_tensor_name: out_of_body_preprocessed
  data_format: hwc
  normalize_means: [0.485, 0.456, 0.406]
  normalize_stds: [0.229, 0.224, 0.225]

out_of_body_inference:
  backend: "trt"
  pre_processor_map:
    "out_of_body": ["out_of_body_preprocessed"]
  inference_map:
    "out_of_body": ["out_of_body_inferred"]
  in_tensor_names: ["out_of_body_preprocessed"]
  out_tensor_names: ["out_of_body_inferred"]
  enable_fp16: true
  parallel_inference: false
  infer_on_cpu: false
  input_on_cuda: true
  output_on_cuda: true
  transmit_on_cuda: true
  is_engine_path: false

out_of_body_postprocessor:
  in_tensor_name: "out_of_body_inferred"
  out_tensor_name: "decision"

detection_preprocessor:
  out_tensor_name: ssd_preprocessed
  out_dtype: "float32"
  resize_width: 300
  resize_height: 300
  scale_min: -1.0
  scale_max: 1.0

segmentation_preprocessor:
  out_tensor_name: seg_preprocessed
  out_dtype: "float32"
  resize_width: 736
  resize_height: 480

multi_ai_inference:
  backend: "trt"
  pre_processor_map:
    "ssd": ["ssd_preprocessed"]
    "tool_seg": ["seg_preprocessed"]
  inference_map:
    "ssd":
      [
        "inference_output_num_detections",
        "inference_output_detection_boxes",
        "inference_output_detection_scores",
        "inference_output_detection_classes",
      ]
    "tool_seg": ["tool_seg_inferred"]
  parallel_inference: true
  infer_on_cpu: false
  enable_fp16: true
  input_on_cuda: true
  output_on_cuda: true
  transmit_on_cuda: true
  is_engine_path: false

detection_postprocessor:
  label_text_size: 0.04
  scores_threshold: 0.5
  label_dict:
    1:
      "text": "Grasper"
      "color": [1.0, 0.0, 1.0]
    2:
      "text": "Bipolar"
      "color": [0.0, 1.0, 0.0]
    3:
      "text": "Hook"
      "color": [1.0, 1.0, 1.0]
    4:
      "text": "Scissors"
      "color": [0.0, 1.0, 1.0]
    5:
      "text": "Clipper"
      "color": [1.0, 0.5, 1.0]
    6:
      "text": "Irrigator"
      "color": [0.5, 0.5, 0.5]
    7:
      "text": "Spec.Bag"
      "color": [1.0, 1.0, 0.0]

segmentation_postprocessor:
  in_tensor_name: tool_seg_inferred
  network_output_type: softmax
  data_format: nchw

deidentification:
  tensor_name: ""
  block_size_h: 40
  block_size_w: 40

holoviz:
  color_lut:
    [
      [0.65, 0.81, 0.89, 0.1],
      [0.2, 0.63, 0.17, 0.7],
      [0.98, 0.6, 0.6, 0.7],
      [0.89, 0.1, 0.11, 0.7],
      [0.99, 0.75, 0.44, 0.7],
      [1.0, 0.5, 0.0, 0.7],
      [0.0, 0.0, 0.0, 0.1],
    ]
